trigger:
- main

name: '1.1.$(DayOfYear)$(rev:rr)'
variables:
  - group: AzureDemoVariables 

jobs:
- job: BuildApple
  pool:
    vmImage: macOS-latest
  steps:
  - checkout: self
    clean: true
    path: "TestApp"
  - task: NodeTool@0 
    inputs:
      versionSpec: '14.x'
  - script: |
      python -m pip install six
    displayName: 'Install six'

  - script: |
      npm i -g nativescript
    displayName: 'Install nativescript'   

  - script: |
      npm --version
      node --version

      ruby --version
      gem query --local
      echo **************************************
      pip --version
      pip show six

    displayName: 'Show NPM version'
  - script: |
      ns --version --json
    displayName: 'Show nativescript version'
  - script: |
      ns doctor
    displayName: 'Run ns doctor'
  
  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: '$(apple_cert_sercure_file_id)'
      certPwd: '$(P12password)'

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install an Apple provisioning profile'
    inputs:
      provProfileSecureFile: '$(apple_provisioning_profile_file_id)'

  - script: |
      #pip install six
      # ns run ios --provision # causes prompt for some reason on machine
      ns build ios --bundle --for-device
    displayName: 'Run ns to build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: |
        **/*.ipa
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true
      preserveTimestamp: true
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
